# run: conda env create --file environment.yml
# include new packages: conda env update --file environment.yml
name: title2doi
channels:
  - conda
dependencies:
- anaconda
- pip
- pip:
   - bs4
   - lxml
   - habanero
- conda:
  - pytest=6.1.2
